default: &default
  adapter: postgresql
  encoding: unicode
  pool: <% ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <% ENV.fetch("POSTGRES_DB_PASSWORD") %?
  host: localhost
  port: 5432

development:
  <<: *default
  database: jeff-badger_development

test:
  <<: *default
  database: jeff-badger_test

production:
  <<: *default
  database: jeff-badger_production 
  username: jeff-badger
  password: <% ENV['JEFF_BADGER_DATABASE_PASSWORD'] %>
